const solutions = [
    {
        name: "VisionAI",
        icon: "vision.png",
        description:
            "An AI application capable of training a new model to recognize a specific product.",
    },
    {
        name: "ChatAI",
        icon: "chat.png",
        description:
            "An AI chatbot that responds exclusively to queries based on a provided custom dataset.",
    },
    {
        name: "ReportAI",
        icon: "report.png",
        description:
            "An AI-powered application that connects to a MySQL database and allows users to generate customizable Excel or CSV reports through natural language input.",
    },
    {
        name: "CodeCanvas AI",
        icon: "code.png",
        description:
            "An AI-powered application that transforms images into front-end code, including HTML,CSS, and JavaScript.",
    },
    {
        name: "Detective AI",
        icon: "detective.png",
        description:
            "An application that identifies whether a piece of text was generated by an AI tool or written by a human.",
    },
];

export default function Solutions() {
    return <div>Integrations</div>;
}
